### ISSUE TITLE
[Bug] 容器预览选择格子导致游戏崩溃

### ISSUE THREAD

**Issue by Grayer0113** [plusls/MasaGadget#108]
### Minecraft Version

1.20.4

### MasaGadget Version

3.2.334-08c8f70

### Description

预览容器时使用鼠标滚轮选择格子立刻崩溃

### To Reproduce

按住alt预览容器
使用鼠标滚轮选择格子

### Log
```
[Render thread/ERROR] (Minecraft) Unreported exception thrown!
java.lang.NullPointerException: Cannot read field "field_22789" because "currentScreen" is null
	at net.minecraft.class_332.handler$feg000$iceberg$renderTooltip(class_332.java:2375) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_51437(class_332.java:646) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_51446(class_332.java:637) ~[client-intermediary.jar:?]
	at com.plusls.MasaGadget.tweakeroo.inventoryPreviewSupportSelect.InventoryOverlayRenderHandler.render(InventoryOverlayRenderHandler.java:191) ~[masa_gadget_mod-1_20_4-3.2.334+08f70-stable-760a0ab27910fca4.jar:?]
	at net.minecraft.class_329.handler$gff001$masa_gadget_mod-1_20_4$onGameOverlayPost(class_329.java:16989) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:401) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:912) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1327) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4-Fabric.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.5.jar:?]
```
### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
请禁用 Iceberg Mod 或尝试关闭 Masa Gadget 的 `容器预览支持选中格子 (inventoryPreviewSupportSelect)` 功能
