### ISSUE TITLE
[Bug] 1.21 崩溃

### ISSUE THREAD

**Issue by MoupiPics** [plusls/MasaGadget#116]
### Minecraft Version

1.21

### MasaGadget Version

4.0.344/4.0.349

### Description

用的masa链接的那个port, 0.8.576magiclib，0.16fabric，0.100.7的fabric API，试图打开tweakeroo GUI导致崩溃

### To Reproduce

![image](https://github.com/user-attachments/assets/4c8fa75b-9d75-49f5-ad56-8c777f2fe652)

### Log
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-07-17 17:49:10
Description: Rendering screen

java.lang.ClassCastException: class fi.dy.masa.tweakeroo.gui.GuiConfigs cannot be cast to class com.plusls.MasaGadget.api.gui.MasaGadgetDropdownList (fi.dy.masa.tweakeroo.gui.GuiConfigs and com.plusls.MasaGadget.api.gui.MasaGadgetDropdownList are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6615435c)
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.masa_gadget_mod$drawMagicConfigGuiDropDownListAgain(WidgetListBase.java:1255)
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.handler$bbh001$masa_gadget_mod$drawMagicConfigGuiDropDownListAgainAfterHover(WidgetListBase.java:1325)
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.drawContents(WidgetListBase.java:441)
	at fi.dy.masa.malilib.gui.GuiListBase.drawContents(GuiListBase.java:178)
	at fi.dy.masa.malilib.gui.GuiBase.method_25394(GuiBase.java:177)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$187(class_757.java)
	at net.minecraft.class_757.wrapOperation$zme000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.masa_gadget_mod$drawMagicConfigGuiDropDownListAgain(WidgetListBase.java:1255)
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.handler$bbh001$masa_gadget_mod$drawMagicConfigGuiDropDownListAgainAfterHover(WidgetListBase.java:1325)
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.drawContents(WidgetListBase.java:441)
	at fi.dy.masa.malilib.gui.GuiListBase.drawContents(GuiListBase.java:178)
	at fi.dy.masa.malilib.gui.GuiBase.method_25394(GuiBase.java:177)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$187(class_757.java)
	at net.minecraft.class_757.wrapOperation$zme000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)

-- Screen render details --
Details:
	Screen name: fi.dy.masa.tweakeroo.gui.GuiConfigs
	Mouse location: Scaled: (213, 120). Absolute: (427.000000, 240.000000)
	Screen size: Scaled: (427, 240). Absolute: (1708, 960). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 42.881s
	Wall uptime: 37.589s
	High-res time: 37.042s
	Client ticks: 690 ticks / 34.500s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Moupi_Pics'/1, l='ClientLevel', x=71.48, y=72.17, z=181.76]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,80,0), Section: (at 0,0,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 25768 game time, 6000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 1

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, itemscroller, litematica, magiclib, magiclib-1_21, magiclib_core, magiclib_malilib_extra, magiclib_minecraft_api, malilib, masa_gadget_mod, minihud, tweakeroo, file/Default-Dark-Mode-1.20.2+-2024.6.0, file/MFP-JH-1522J.zip, file/Xekr方纹淡彩改-1.20

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Mac OS X (aarch64) version 12.7.4
	Java Version: 22.0.1, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 156686256 bytes (149 MiB) / 1006632960 bytes (960 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M2
	Identifier: Apple Inc. Family 0xda33d83d Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Avalanche + Blizzard
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M2
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MiB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MiB): 23552.00
	Virtual memory used (MiB): 18421.52
	Swap memory total (MiB): 7168.00
	Swap memory used (MiB): 5710.63
	Space in storage for jna.tmpdir (MiB): available: 225077.09, total: 948584.19
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 225077.09, total: 948584.19
	Space in storage for io.netty.native.workdir (MiB): available: 225077.09, total: 948584.19
	Space in storage for java.io.tmpdir (MiB): available: 225077.09, total: 948584.19
	Space in storage for workdir (MiB): available: 225077.09, total: 948584.19
	JVM Flags: 10 total; -Xmx12288m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods
	Fabric Mods: 
		fabric-api: Fabric API 0.100.7+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.15+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.18+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.2+c111832ad1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.25+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.12+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.3+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.13+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.1+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.13+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.25+5bd9f1bcd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.82+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		itemscroller: Item Scroller 0.23.999-sakura.4
		java: OpenJDK 64-Bit Server VM 22
		litematica: Litematica 0.18.999-sakura.20
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.2.0+7e687b32d1
		magiclib: MagicLib 0.8.576+9192507-stable
			magiclib-1_21: MagicLib Legacy Compat for 1.21 0.8.23+079e864-stable
			magiclib_core: MagicLib Core API 0.8.114+9ceb5c7-stable
			magiclib_malilib_extra: MagicLib Malilib API 0.8.41+079e864-stable
			magiclib_minecraft_api: MagicLib Minecraft API 0.6.59+079e864-stable
		malilib: MaLiLib 0.19.999-sakura.8
		masa_gadget_mod: Masa Gadget 4.0.349+97826a4-beta
		minecraft: Minecraft 1.21
		minihud: MiniHUD 0.31.999-sakura.9
		tweakeroo: Tweakeroo 0.20.999-sakura.17
	Launched Version: 1.21-0
	Launcher name: HMCL
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Apple M2 GL version 4.1 Metal - 76.3, Apple
	Window size: 1708x960
	GFLW Platform: cocoa
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, itemscroller, litematica, magiclib, magiclib-1_21, magiclib_core, magiclib_malilib_extra (incompatible), magiclib_minecraft_api (incompatible), malilib, masa_gadget_mod, minihud, tweakeroo (incompatible), file/Default-Dark-Mode-1.20.2+-2024.6.0, file/MFP-JH-1522J.zip (incompatible), file/Xekr方纹淡彩改-1.20 (incompatible)
	Current Language: en_us
	Locale: en_SG
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: 8x Apple M2
	Server Running: true
	Player Count: 1 / 8; [class_3222['Moupi_Pics'/1, l='ServerLevel[New World]', x=71.48, y=72.17, z=181.76]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 6453310870614483705
```
### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
已确认到原因，等待修复，请将安装 ModMenu 作为临时解决方案

**Comment by Hendrix-Shen** [comment]
试一下这个版本 [4.0.350-beta](https://github.com/plusls/MasaGadget/actions/runs/9975421170)

**Comment by md606** [comment]
感谢！新版没问题了，4.0.349在预览容器的时候也会崩溃，现在好了🥰

**Comment by MoupiPics** [comment]
> 已确认到原因，等待修复，请将安装 ModMenu 作为临时解决方案

草原来是这个原因（
我从1.20迁移迁一半（
