### ISSUE TITLE
[Bug] 图书馆村民显示闪退

### ISSUE THREAD

**Issue by Adogs1** [plusls/MasaGadget#118]
### Minecraft Version

1.21

### MasaGadget Version

MasaGadget-mc1.21-fabric-4.0.355-stable

### Description

我在1.21使用masa全家桶，是Bilibili的up开发的https://www.bilibili.com/video/BV1Ey411B7VL/?spm_id_from=333.999.0.0
但在我打开渲染图书馆村民渲染的第一本附魔书时，我在我本地部署的服务器上放置了一个村民，我大概开到村民绑定了讲台，然后我的客户端就闪退了，带有日志，服务端没缺少魔法类库mod

**Comment by Hendrix-Shen** [comment]
少判了一个条件，最近有事，过两天会修，可以开启 ` 渲染村民交易的第一本附魔书 (renderTradeEnchantedBook)` 作为临时解决方案以缓解此问题。

**Comment by Hendrix-Shen** [comment]
试一下这个版本：[4.0.357-beta](https://github.com/plusls/MasaGadget/actions/runs/10161419395)

**Comment by LDmoxeii** [comment]
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-08-01 19:07:05
Description: Unexpected error

java.lang.RuntimeException: Exception occurs while delegating events.
  Event class: top.hendrixshen.magiclib.impl.event.minecraft.render.RenderLevelEvent$PostRender
	at top.hendrixshen.magiclib.impl.event.EventManager.dispatchImpl(EventManager.java:51)
	at top.hendrixshen.magiclib.impl.event.EventManager.dispatch(EventManager.java:33)
	at net.minecraft.class_761.handler$fea000$magiclib_minecraft_api$postRenderLevel(class_761.java:12266)
	at net.minecraft.class_761.method_22710(class_761.java:1291)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.IllegalStateException: Cannot load Villager offers on the client
	at net.minecraft.class_3988.method_8264(class_3988.java:109)
	at net.minecraft.class_1646.method_7237(class_1646.java:898)
	at net.minecraft.class_3988.masa_gadget$safeGetOffers(class_3988.java:531)
	at com.plusls.MasaGadget.impl.feature.entityInfo.VillagerNextRestockTimeInfo.needsRestock(VillagerNextRestockTimeInfo.java:65)
	at com.plusls.MasaGadget.impl.feature.entityInfo.VillagerNextRestockTimeInfo.getInfo(VillagerNextRestockTimeInfo.java:44)
	at com.plusls.MasaGadget.impl.feature.entityInfo.EntityInfoRenderer.postRenderLevel(EntityInfoRenderer.java:71)
	at top.hendrixshen.magiclib.impl.event.minecraft.render.RenderLevelEvent$PostRender.dispatch(RenderLevelEvent.java:75)
	at top.hendrixshen.magiclib.impl.event.EventManager.dispatchImpl(EventManager.java:48)
	... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at top.hendrixshen.magiclib.impl.event.EventManager.dispatchImpl(EventManager.java:51)
	at top.hendrixshen.magiclib.impl.event.EventManager.dispatch(EventManager.java:33)
	at net.minecraft.class_761.handler$fea000$magiclib_minecraft_api$postRenderLevel(class_761.java:12266)
	at net.minecraft.class_761.method_22710(class_761.java:1291)
	at net.minecraft.class_757.method_3188(class_757.java:1087)

-- Uptime --
Details:
	JVM uptime: 93.429s
	Wall uptime: 79.092s
	High-res time: 73.534s
	Client ticks: 1242 ticks / 62.100s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Affected level --
Details:
	All players: 1 total; [class_746['LD_moxeii'/14, l='ClientLevel', x=320.76, y=71.98, z=-107.68]]
	Chunk stats: 1024, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (4,66,15), Section: (at 4,2,15 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2175525 game time, 221483 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 184

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, annotationtoolbox, appleskin, betterf3, caffeineconfig, carpet, carpet-ams-addition, carpet-extra, carpet-org-addition, carpet-tis-addition, cloth-config, conditional-mixin, continuity, custom-crosshair-mod, emi, enhancedblockentities, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fpsreducer, gca, imblocker, indium, inventoryprofilesnext, iris, itemscroller, jade, kyrptconfig, lanserverproperties, libipn, litematica, lithium, magiclib, magiclib-1_21, magiclib_core, magiclib_malilib_extra, magiclib_minecraft_api, malilib, masa_gadget_mod, minihud, modmenu, placeholder-api, quickshulker, reeses-sodium-options, sodium, sodium-extra, syncmatica, tweakermore, tweakeroo, world_preview, xaerominimap, xaeroplus, xaeroworldmap, continuity:default, continuity:glass_pane_culling_fix, file/XKRD 红显v3.3for1.21.zip, file/[1.21]MASA全家桶汉化包.zip

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 412154784 bytes (393 MiB) / 1665138688 bytes (1588 MiB) up to 5045747712 bytes (4812 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 6800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 68 Stepping 1
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 2048.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.21024.2004
	Memory slot #0 capacity (MiB): 4096.00
	Memory slot #0 clockSpeed (GHz): 6.40
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 4096.00
	Memory slot #1 clockSpeed (GHz): 6.40
	Memory slot #1 type: Unknown
	Memory slot #2 capacity (MiB): 4096.00
	Memory slot #2 clockSpeed (GHz): 6.40
	Memory slot #2 type: Unknown
	Memory slot #3 capacity (MiB): 4096.00
	Memory slot #3 clockSpeed (GHz): 6.40
	Memory slot #3 type: Unknown
	Virtual memory max (MiB): 28356.95
	Virtual memory used (MiB): 13806.64
	Swap memory total (MiB): 14336.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 41351.80, total: 176754.89
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 41351.80, total: 176754.89
	Space in storage for io.netty.native.workdir (MiB): available: 41351.80, total: 176754.89
	Space in storage for java.io.tmpdir (MiB): available: 42054.41, total: 174086.95
	Space in storage for workdir (MiB): available: 41351.80, total: 176754.89
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn721m -Xmx4812m
	Fabric Mods: 
		appleskin: AppleSkin 3.0.2+mc1.21
		betterf3: BetterF3 11.0.1
		carpet: Carpet Mod 1.4.147+v240613
		carpet-ams-addition: Carpet AMS Addition 2.45.1
			annotationtoolbox: AnnotationToolBox 0.3
			com_esotericsoftware_yamlbeans_yamlbeans: yamlbeans 1.17
			mixinextras: MixinExtras 0.4.0
		carpet-extra: Carpet Extra 1.4.147
		carpet-org-addition: Carpet Org Addition v1.32.0-2407270138
		carpet-tis-addition: Carpet TIS Addition 1.61.1
			conditional-mixin: conditional mixin 0.6.2
		cloth-config: Cloth Config v15 15.0.128
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.5+1.21
		custom-crosshair-mod: Custom Crosshair Mod 1.6.0-fabric
		emi: EMI 1.1.10+1.21+fabric
		enhancedblockentities: Enhanced Block Entities 0.10.1+1.21
		fabric-api: Fabric API 0.100.7+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.15+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.18+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.2+c111832ad1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.25+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.12+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.3+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.13+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.1+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.13+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.25+5bd9f1bcd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.2.0+7e687b32d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.82+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
		fpsreducer: FPS Reducer 1.21-2.9
		gca: GugleCarpetAddition mc1.21-2.9.0+build.52
		imblocker: IMBlocker 4.0.9b
		indium: Indium 1.0.34+mc1.21
		inventoryprofilesnext: Inventory Profiles Next 2.0.3
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		itemscroller: Item Scroller 0.23.999-sakura.2
		jade: Jade 15.1.5+fabric
		java: OpenJDK 64-Bit Server VM 21
		lanserverproperties: Lan Server Properties 1.13
		libipn: libIPN 6.0.1
		litematica: Litematica 0.18.999-sakura.9
		lithium: Lithium 0.12.7
		magiclib: MagicLib 0.8.576+9192507-stable
			magiclib-1_21: MagicLib Legacy Compat for 1.21 0.8.23+079e864-stable
			magiclib_core: MagicLib Core API 0.8.114+9ceb5c7-stable
			magiclib_malilib_extra: MagicLib Malilib API 0.8.41+079e864-stable
			magiclib_minecraft_api: MagicLib Minecraft API 0.6.59+079e864-stable
		malilib: MaLiLib 0.19.999-sakura.4
		masa_gadget_mod: Masa Gadget 4.0.357+d696798-beta
		minecraft: Minecraft 1.21
		minihud: MiniHUD 0.31.999-sakura.3
		modmenu: Mod Menu 11.0.1
		placeholder-api: Placeholder API 2.4.1+1.21
		quickshulker: Quick Shulker 1.4.4-1.21
			kyrptconfig: Kyrpt Config 1.6.0-1.20.4
		reeses-sodium-options: Reese's Sodium Options 1.7.3+mc1.21
		sodium: Sodium 0.5.11+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		syncmatica: Syncmatica 0.3.12-sakura.4
		tweakermore: TweakerMore 3.20.1
		tweakeroo: Tweakeroo 0.20.999-sakura.8
		world_preview: World preview 1.3.0
		xaerominimap: Xaero's Minimap 24.2.1
		xaeroplus: XaeroPlus 2.20
			com_github_ben-manes_caffeine_caffeine: caffeine 3.1.8
			net_lenni0451_lambdaevents: LambdaEvents 2.4.2
		xaeroworldmap: Xaero's World Map 1.38.8
	Loaded Shaderpack: (off)
	Launched Version: 1.21-Fabric 0.15.11
	Launcher name: PCL
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.0 Core Profile Context 23.10.24.02.230811, ATI Technologies Inc.
	Window size: 2880x1755
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, annotationtoolbox, appleskin (incompatible), betterf3, caffeineconfig, carpet, carpet-ams-addition, carpet-extra, carpet-org-addition, carpet-tis-addition, cloth-config, conditional-mixin, continuity, custom-crosshair-mod, emi, enhancedblockentities, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fpsreducer, gca, imblocker (incompatible), indium, inventoryprofilesnext, iris, itemscroller, jade (incompatible), kyrptconfig, lanserverproperties, libipn, litematica, lithium, magiclib, magiclib-1_21, magiclib_core, magiclib_malilib_extra (incompatible), magiclib_minecraft_api (incompatible), malilib, masa_gadget_mod, minihud, modmenu, placeholder-api, quickshulker, reeses-sodium-options, sodium, sodium-extra, syncmatica, tweakermore, tweakeroo (incompatible), world_preview, xaerominimap (incompatible), xaeroplus, xaeroworldmap (incompatible), continuity:default, continuity:glass_pane_culling_fix, file/XKRD 红显v3.3for1.21.zip, file/[1.21]MASA全家桶汉化包.zip
	Current Language: zh_cn
	Locale: zh_CN
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: 16x AMD Ryzen 7 6800H with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['LD_moxeii'/14, l='ServerLevel[荣集生存]', x=320.76, y=71.98, z=-107.68]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2, world_preview, file/AmsData (incompatible)
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, file/AmsData (incompatible), trade_rebalance, vanilla, world_preview
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 5210291057477252618
```
在开启补货cd和村民第一本附魔书的同时，杀死图书管理员村民闪退

**Comment by Hendrix-Shen** [comment]
试一下这个版本：[4.0.364-beta](https://github.com/plusls/MasaGadget/actions/runs/10213825485)
