### ISSUE TITLE
Crash in 1.18

### ISSUE THREAD

**Issue by boasbakker** [plusls/MasaGadget#18]
When using my own modified versions of the masa mods for 1.18 the game crashes.
Also why did you make an 1.18 version when there are no masa mods for 1.18?
[15:56:21] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NoClassDefFoundError: net/fabricmc/loader/util/version/VersionPredicateParser
	at com.plusls.MasaGadget.MasaGadgetMixinPlugin.checkDependency(MasaGadgetMixinPlugin.java:234) ~[MasaGadget-fabric-21w38a-2.0.5.jar:?]
	at com.plusls.MasaGadget.config.Configs$Tweakeroo.lambda$static$0(Configs.java:160) ~[MasaGadget-fabric-21w38a-2.0.5.jar:?]
	at java.util.Collection.removeIf(Collection.java:576) ~[?:?]
	at com.plusls.MasaGadget.config.Configs$Tweakeroo.<clinit>(Configs.java:158) ~[MasaGadget-fabric-21w38a-2.0.5.jar:?]
	at com.plusls.MasaGadget.tweakeroo.inventoryPreviewSupportSelect.MouseScrollInputHandler.onMouseClick(MouseScrollInputHandler.java:33) ~[MasaGadget-fabric-21w38a-2.0.5.jar:?]
	at fi.dy.masa.malilib.event.InputEventHandler.onMouseClick(InputEventHandler.java:178) ~[malilib-fabric-1.17.1-0.10.0-dev.25.jar:?]
	at net.minecraft.class_312.handler$ccp000$hookOnMouseClick(class_312.java:2556) ~[intermediary-minecraft-21w40a-client.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:54) ~[intermediary-minecraft-21w40a-client.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[intermediary-minecraft-21w40a-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-minecraft-21w40a-client.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[intermediary-minecraft-21w40a-client.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133) ~[FpsReducer-fabric-1.23-beta1-mc1.18.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.handler$bnn000$handleWaitEventsTimeout(RenderSystem.java:1420) ~[intermediary-minecraft-21w40a-client.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java) ~[intermediary-minecraft-21w40a-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1147) ~[intermediary-minecraft-21w40a-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:735) [intermediary-minecraft-21w40a-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [intermediary-minecraft-21w40a-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-loader-0.12.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.12.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.util.version.VersionPredicateParser
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 36 more
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 15/10/2021, 15:56
Description: Unexpected error

java.lang.NoClassDefFoundError: net/fabricmc/loader/util/version/VersionPredicateParser
	at com.plusls.MasaGadget.MasaGadgetMixinPlugin.checkDependency(MasaGadgetMixinPlugin.java:234)
	at com.plusls.MasaGadget.config.Configs$Tweakeroo.lambda$static$0(Configs.java:160)
	at java.base/java.util.Collection.removeIf(Collection.java:576)
	at com.plusls.MasaGadget.config.Configs$Tweakeroo.<clinit>(Configs.java:158)
	at com.plusls.MasaGadget.tweakeroo.inventoryPreviewSupportSelect.MouseScrollInputHandler.onMouseClick(MouseScrollInputHandler.java:33)
	at fi.dy.masa.malilib.event.InputEventHandler.onMouseClick(InputEventHandler.java:178)
	at net.minecraft.class_312.handler$ccp000$hookOnMouseClick(class_312.java:2556)
	at net.minecraft.class_312.method_1601(class_312.java:54)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.handler$bnn000$handleWaitEventsTimeout(RenderSystem.java:1420)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java)
	at net.minecraft.class_310.method_1523(class_310.java:1147)
	at net.minecraft.class_310.method_1514(class_310.java:735)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.util.version.VersionPredicateParser
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 36 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.plusls.MasaGadget.MasaGadgetMixinPlugin.checkDependency(MasaGadgetMixinPlugin.java:234)
	at com.plusls.MasaGadget.config.Configs$Tweakeroo.lambda$static$0(Configs.java:160)
	at java.base/java.util.Collection.removeIf(Collection.java:576)
	at com.plusls.MasaGadget.config.Configs$Tweakeroo.<clinit>(Configs.java:158)
	at com.plusls.MasaGadget.tweakeroo.inventoryPreviewSupportSelect.MouseScrollInputHandler.onMouseClick(MouseScrollInputHandler.java:33)
	at fi.dy.masa.malilib.event.InputEventHandler.onMouseClick(InputEventHandler.java:178)
	at net.minecraft.class_312.handler$ccp000$hookOnMouseClick(class_312.java:2556)
	at net.minecraft.class_312.method_1601(class_312.java:54)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.handler$bnn000$handleWaitEventsTimeout(RenderSystem.java:1420)
Mixins in Stacktrace: Failed to find Mixin metadata: java.lang.NoSuchMethodException: org.spongepowered.asm.mixin.transformer.ClassInfo.getMixins()

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, test.zip, Planked_Signposts, 1.17 pack, textureapck, BLUE ICE, better_tinted_glass, Black Icons, mini-ad-recourcepack.zip, BetterCopper, no optifine lower sides.zip, sietse.zip, continuity/glass_pane_culling_fix, Ore_Outlines, CTM 1.14.zip, continuity/default, mtt-connected-textures-e2290.zip, infested-blocks-caution-tape.zip, Connected Chains.zip
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2418)
	at net.minecraft.class_310.method_1514(class_310.java:759)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Mixins in Stacktrace: Failed to find Mixin metadata: java.lang.NoSuchMethodException: org.spongepowered.asm.mixin.transformer.ClassInfo.getMixins()

-- System Details --
Details:
	Minecraft Version: 21w40a
	Minecraft Version ID: 21w40a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1311006864 bytes (1250 MiB) / 2147483648 bytes (2048 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-10105F CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 3,70
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048,00
	Graphics card #0 deviceId: 0x1c81
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5751
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32689,72
	Virtual memory used (MB): 18729,30
	Swap memory total (MB): 16384,00
	Swap memory used (MB): 180,96
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx6144m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 21w39a-fabric0.40.5-1.2.1
		antighost: AntiGhost 21w37a-fabric0.40.1-1.1.4
		architectury: Architectury 3.0.29
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoswitch: AutoSwitch 3.4.0
		autoswitch-api: AutoSwitch API 1.0.0
		beenfo: Beenfo 21w39a-fabric0.40.5-1.3.2
		betterbiomeblend: Better Biome Blend 1.17.0-1.1.4-fabric
		betterpingdisplay: Better Ping Display 1.1
		betterrecipebook: Better Recipe Book 1.5.2
		brandpacket: brandpacket 0.0.2.1
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.5.39
		c2me-fabric_libs_: libs 0.2.0+alpha.5.39
		carpet: Carpet Mod 1.4.47
		carpet-tctc-addition: CarpetTCTCAddition 1.1.3+build.15
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cleardespawn: Clear Despawn 21w40a-1.1.3
		clickthrough: ClickThrough 21w37a-fabric0.40.1-0.4
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config: Cloth Config v6 6.0.39
		continuity: Continuity 1.0.0+1.17
		convenient-mobgriefing: Convenient mobGriefing 2.0.2
		crowdin-translate: CrowdinTranslate 1.3+1.17
		cullleaves: Cull Leaves 2.3.0
		dark-loading-screen: Dark Loading Screen 1.6.9
		dcch: DCCH 2.0+1.17
		draggable-resource-packs: Draggable Resource Packs 1.0.1
		durabilityviewer: Giselbaers Durability Viewer 21w39a-fabric0.40.5-1.10.1
		dynamic-surroundings: Dynamic-Surroundings 1.1
		easiercrafting: EasierCrafting 21w39a-fabric0.40.5-1.7
		easiervillagertrading: EasierVillagerTrading 21w39a-fabric0.40.5-1.5.4
		eatinganimationid: Eating Animation 1.2
		eggtab: Egg Tab 2.1.0+1.16-fabric
		enchlevel-langpatch: Enchantment Level Language Patch 0.2.0
		entityoutliner: Entity Outliner 1.2.0
		environmentalcreepers: Environmental Creepers 1.6.0
		fabric: Fabric API 0.40.8+1.18
		fabric-api-base: Fabric API Base 0.3.0+a02b446382
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931882
		fabric-biome-api-v1: Fabric Biome API (v1) 4.0.3+d1937ce482
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446382
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c82
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa82
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931882
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931882
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31082
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.1+d1937ce482
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+8f2c3e0482
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.12+dc3d5c4782
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa82
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931882
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931882
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612182
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931882
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e82
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.6+d1937ce482
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446382
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa82
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446382
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+6eb8b35a82
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa82
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931882
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446382
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446382
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+c683a65582
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.6+dc3d5c4782
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931882
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.4+c683a65582
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.2.0+8f2c3e0482
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223082
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.5+c683a65582
		fabric-rendering-v1: Fabric Rendering (v1) 1.9.0+c683a65582
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b82
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+cbda931882
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931882
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.2+6eb8b35a82
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+8f2c3e0482
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446382
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612182
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.0+c683a65582
		fabricloader: Fabric Loader 0.12.1
		fabrishot: Fabrishot 1.5.1
		fallingleaves: Falling Leaves 1.7.3+1.17.1
		fpsreducer: FPS Reducer 1.23-beta1-mc1.18
		gbfabrictools: GBfabrictools 1.3.4+1.17
		here-be-no-dragons: Here be no Dragons! 1.0.0
		indium: Indium 1.0.0-dev.eb838d0+mc21w40a-dirty
		interactic: Interactic 0.1.6-1.17
		invmove: InvMove 1.17-0.1.0
		iris: Iris 1.1.3-pre+rev.5941e4a
		isometric-renders: Isometric Renders 0.2.7-21w39a
		itemscroller: Item Scroller 0.15.0-dev.20210707.005506
		java: Java HotSpot(TM) 64-Bit Server VM 16
		lambdabettergrass: LambdaBetterGrass 1.2.1+1.17
		lazydfu: LazyDFU 0.1.2
		lightoverlay: Light Overlay 6.0.0
		malilib: MaLiLib 0.10.0-dev.24
		masa_gadget_mod: Masa Gadget 21w38a-2.0.5
		mcwifipnp: LAN World Plug-n-Play 1.5.0
		memoryusagescreen: Memory Usage Screen 1.2
		midnightlib: MidnightLib 0.2.5
		minecraft: Minecraft 1.18-alpha.21.40.a
		minihud: MiniHUD 0.19.0-dev.20210906.231818
		mixintrace: MixinTrace 1.1.0+1.17
		modmenu: Mod Menu 3.0.0
		moretags: More Tags 1.4.8
		multiconnect-api: MultiConnect API 1.4.15
		nethermap: Better Nether Map 1.5.0-1.18
		offlineskins: OfflineSkins 1.17.1-v2-fabric
		org_aeonbits_owner_owner: owner 1.0.12
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_joml_joml: joml 1.10.2
		org_yaml_snakeyaml: snakeyaml 1.29
		pickblockpro: Pick Block Pro 1.5.1-beta
		sodium: Sodium 0.3.2+IRIS2-rev.e480fc7-dirty
		spruceui: SpruceUI 3.3.0+1.17
		statssearch: StatsSearch 21w40a-fabric0.40.7-1.0.1
		stepup: StepUp 21w40a-fabric0.40.7-1.1
		timechanger: Time Changer 1.0.0
		tweakeroo: Tweakeroo 0.10.0-dev.20210912.004443
		viafabric: ViaFabric 0.4.3+232-main
		viafabric-mc118: ViaFabric for 1.18 0.4.3+232-main
		viaversion: ViaVersion 4.1.0-21w40a-SNAPSHOT
		voicechat: Simple Voice Chat 21w38a-1.0.0
		wi_zoom: WI Zoom 1.3-MC21w41a
		worldmesher: Worldmesher 0.1-21w39a
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050/PCIe/SSE2 GL version 3.2.0 NVIDIA 457.51, NVIDIA Corporation
	Window size: 1378x877
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/test.zip (incompatible), file/Planked_Signposts (incompatible), file/1.17 pack (incompatible), file/textureapck (incompatible), file/BLUE ICE (incompatible), file/better_tinted_glass (incompatible), Black Icons (incompatible), file/mini-ad-recourcepack.zip (incompatible), file/BetterCopper (incompatible), file/no optifine lower sides.zip (incompatible), file/sietse.zip (incompatible), continuity/glass_pane_culling_fix (incompatible), file/Ore_Outlines (incompatible), file/CTM 1.14.zip (incompatible), continuity/default (incompatible), file/mtt-connected-textures-e2290.zip (incompatible), file/infested-blocks-caution-tape.zip (incompatible), file/Connected Chains.zip (incompatible)
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i3-10105F CPU @ 3.70GHz
#@!@# Game crashed! Crash report saved to: #@!@# D:\boas\Minecraft\MultiMC\instances\1.17.11\.minecraft\crash-reports\crash-2021-10-15_15.56.21-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.

**Comment by Hendrix-Shen** [comment]
Older version is broken with Fabric Loader **0.12.x**. 
Please try the latest develop version(https://github.com/plusls/MasaGadget/actions/runs/1345999449).
