### ISSUE TITLE
MasaGadget crashing with last tweakeroo version

### ISSUE THREAD

**Issue by Lokemol** [plusls/MasaGadget#25]
So, Masa said that this was crashing thanks to failing to mixin into a tweakeroo method, idk about this, so, this is the crash report, thanks!

---- Minecraft Crash Report ----
// There are four lights!

Time: 12/12/21, 5:23 PM
Description: Unexpected error

java.lang.RuntimeException: Mixin transformation of fi.dy.masa.tweakeroo.renderer.RenderUtils failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:224)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at fi.dy.masa.tweakeroo.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:42)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:66)
	at net.minecraft.class_329.handler$djp000$onGameOverlayPost(class_329.java:3481)
	at net.minecraft.class_329.method_1753(class_329.java:406)
	at net.minecraft.class_757.method_3192(class_757.java:855)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
	... 18 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in fi/dy/masa/tweakeroo/renderer/RenderUtils::renderInventoryOverlay(Lnet/minecraft/class_310;Lnet/minecraft/class_4587;)V has incompatible changes at opcode 125 in callback masa_gadget_mod.mixins.json:tweakeroo.inventoryPreviewSupportShulkerBoxItemEntity.MixinRenderUtils->@Inject::getTraceEntity(Lnet/minecraft/class_310;Lnet/minecraft/class_4587;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_239;Lnet/minecraft/class_1263;Lnet/minecraft/class_2480;Lnet/minecraft/class_1309;Lnet/minecraft/class_1297;)V from mod masa_gadget_mod.
 Expected: [Lnet/minecraft/class_1937;, Lnet/minecraft/class_1657;, Lnet/minecraft/class_239;, Lnet/minecraft/class_1263;, Lnet/minecraft/class_2480;, Lnet/minecraft/class_1309;, Lnet/minecraft/class_1297;]
    Found: [Lnet/minecraft/class_1937;, Lnet/minecraft/class_1297;, Lnet/minecraft/class_239;, Lnet/minecraft/class_1263;, Lnet/minecraft/class_2480;, Lnet/minecraft/class_1309;, Lnet/minecraft/class_1297;]
Available: [Lnet/minecraft/class_1937;, Lnet/minecraft/class_1297;, Lnet/minecraft/class_239;, Lnet/minecraft/class_1263;, Lnet/minecraft/class_2480;, Lnet/minecraft/class_1309;, Lnet/minecraft/class_1297;]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:545)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:495)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1374)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:224)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at fi.dy.masa.tweakeroo.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:42)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:66)
	at net.minecraft.class_329.handler$djp000$onGameOverlayPost(class_329.java:3481)
	at net.minecraft.class_329.method_1753(class_329.java:406)

-- Affected level --
Details:
	All players: 1 total; [class_746['Lokemol'/269200, l='ClientLevel', x=-122.25, y=191.55, z=165.16]]
	Chunk stats: 4096, 1260
	Level dimension: minecraft:overworld
	Level spawn location: World: (-208,70,96), Section: (at 0,6,0 in -13,4,6; chunk contains blocks -208,0,96 to -193,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 204228576 game time, 280518477 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Fabric Mods, Default, VanillaTweaks_r558410.zip, XeKr+redstone+display1.17-V2.zip, OwO_Observers.zip, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 337670600 bytes (322 MiB) / 1006632960 bytes (960 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2484
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9676
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 42940.62
	Virtual memory used (MB): 18512.24
	Swap memory total (MB): 10240.00
	Swap memory used (MB): 8.13
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		architectury: Architectury 2.6.35
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bedrockminer: Bedrock Miner 1.0.0
		betterthanmending: BetterThanMending 1.3.0
		blue_endless_jankson: jankson 1.2.1
		carpet: Carpet Mod 1.4.56
		carpet-extra: Carpet Extra 1.4.51
		carpet-fixes: Carpet Fixes 1.17.1-1.2.0+v211021
		carpet-tis-addition: Carpet TIS Addition 1.24.0+build.742
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config2: Cloth Config v5 5.1.40
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		deepslatecutting: Deepslate Cutting 1.2.2
		enhancedblockentities: Enhanced Block Entities 0.5+1.17
		essentialaddons: Essential Addons 1.17.1-1.0.6
		fabric: Fabric API 0.42.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
		fabric-language-kotlin: Fabric Language Kotlin 1.6.3+kotlin.1.5.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
		fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+6d0fac4218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+6d0fac4218
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+6d0fac4218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
		fabricloader: Fabric Loader 0.12.5
		fallingtree: FallingTree 2.13.0
		ferritecore: FerriteCore 3.1.0
		flan: Flan 1.17.1-1.6.1
		flytre_lib: FlytreLib 0.2.21
		grindenchantments: Grind Enchantments 1.3.0+1.17.1
		harvest: Harvest 1.2.12
		hydrogen: Hydrogen 0.3
		inmis: Inmis 2.3.2-1.17.1
		inventorysorter: Inventory Sorter 1.7.9-1.17
		iris: Iris 1.1.3-starline+build.665
		itemscroller: Item Scroller craftfix-1.2.6
		java: OpenJDK 64-Bit Server VM 16
		krypton: Krypton 0.1.4
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lazydfu: LazyDFU 0.1.2
		litematica: Litematica 0.0.0-dev.20210906.183617
		lithium: Lithium 0.7.5
		malilib: MaLiLib 0.10.0-dev.26
		masa_gadget_mod: Masa Gadget 1.17.1-2.0.6
		maybe-more-data: Maybe More Data 1.0.0-1.17.1
		memoryleakfix: memory Leak Fix 1.17.1-0.1.1
		minecraft: Minecraft 1.17.1
		minihud: MiniHUD 0.19.0-dev.20210707.150016
		minitweaks: MiniTweaks 1.1.3
		modmenu: Mod Menu 2.0.14
		monsters_in_the_closet: Monsters in the Closet 1.0.2+1.17
		multiconnect-api: MultiConnect API 1.4.15
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		no_fog: No Fog 1.1.0+1.17.1
		offlineskins: OfflineSkins 1.17.1-v1-fabric
		omega-config: OmegaConfig 1.0.4
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		org_joml_joml: joml 1.10.2
		org_yaml_snakeyaml: snakeyaml 1.29
		pca: Plusls carpet addition mod 1.17.1-0.2.1
		perfectaccuracy: Perfect Accuracy 1.1
		pistorder: Pistorder 1.4.4
		recipecache: recipecache 0.2.1-1.17.1
		replaymod: Replay Mod 1.17.1-2.6.1
		roughlyenoughitems: Roughly Enough Items 6.2.335
		sodium: Sodium 0.3.3+build.8
		sodium-extra: Sodium Extra 0.3.6
		spark: spark 1.6.2
		subtick: Sub Tick 1.17.1-1.4.0
		syncmatica: Syncmatica 0.2.6
		tweakeroo: Tweakeroo 0.10.0-dev.20211201.002419
		worldedit: WorldEdit 7.2.7+9f3e795
		worldspecificviewdistance: World Specific View Distance 0.1.0-1.17
		xaerominimap: Xaero's Minimap 21.22.2
		xaeroworldmap: Xaero's World Map 1.18.3
		xpbeacons: Experience Beacons 7.0
		zickcarpet: Zick Carpet 1.0.1
	Launched Version: fabric-loader-0.12.5-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 496.76, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods, vanilla, file/VanillaTweaks_r558410.zip, file/XeKr+redstone+display1.17-V2.zip, file/OwO_Observers.zip (incompatible)
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz

**Comment by plusls** [comment]
try the version in GitHub action.
