### ISSUE TITLE
[Bug] 1.18.2中使用2.0.8版本的mod启动时异常

### ISSUE THREAD

**Issue by XiaoHuiHui233** [plusls/MasaGadget#37]
### Minecraft Version

1.18.2

### MasaGadget Version

2.0.8

### Description

启动过程中发生crash：
```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'masa_gadget_mod'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_3195 fi.dy.masa.minihud.util.StructureType.getFeature()'
	at com.plusls.MasaGadget.minihud.compactBborProtocol.BborProtocol.<clinit>(BborProtocol.java:43)
	at com.plusls.MasaGadget.MasaGadgetMod.onInitializeClient(MasaGadgetMod.java:21)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
```
看起来好像是和minihud也有关，可以提供的版本细节如下：
fabric loader: 0.13.3
fabric api: 0.48.0
minihud: 0.22.0 （发布于2022-03-04）

另外在latest.log里发现了一个不知道算不算小虫的东西：
```
[14:14:30] [ForkJoinPool-1-worker-4/WARN]: The mod "masa_gadget_mod" contains invalid entries in its mod json:
- Unsupported root entry "injectors" at line 45 column 14
```

### To Reproduce

Just start the game.

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
是否能提供更完整的日志（crash-report&full log）？没能复现这个问题。

**Comment by XiaoHuiHui233** [comment]
crash-report: [见此](https://gist.githubusercontent.com/XiaoHuiHui233/4c18a4a0da91aeb9e55e1561540d1e16/raw/24915fff35d8626e1dc352331319db67cf3525da/crash-2022-03-14_14.14.49-client.txt)
full log: [见此](https://gist.githubusercontent.com/XiaoHuiHui233/61f434828003c6ba983cffdde8bc3bca/raw/2dbae4e8f09397fa23ba260cdb6906de7e717a7d/latest.log)

**Comment by Hendrix-Shen** [comment]
看起来像是在使用 Release 中的正式版，是否尝试过 [CI#203](https://github.com/plusls/MasaGadget/actions/runs/1951365670)？

**Comment by XiaoHuiHui233** [comment]
我的问题了 我以为你们CI会发到Release里。。[CI#203](https://github.com/plusls/MasaGadget/actions/runs/1951365670)没问题。期待尽快正式版。
