### ISSUE TITLE
請問能更新到1.17版本嗎?

### ISSUE THREAD

**Issue by ktisme** [plusls/MasaGadget#6]
這模組對於使用MASA的模組真的很方便，希望能更新到1.17版本~

**Comment by DragonEggBedrockBreaking** [comment]
This would be useful on 1.17

**Comment by DragonEggBedrockBreaking** [comment]
I just tested: the mod doesn't crash on startup, but it crashes in game when trying to use it, e.g. when I try to press alt to preview a chest, I get this crash:
```
---- Minecraft Crash Report ----
// My bad.

Time: 18/06/2021, 22:26
Description: Unexpected error

java.lang.NoSuchMethodError: 'void com.mojang.blaze3d.systems.RenderSystem.pushMatrix()'
	at Not Enough Crashes deobfuscated stack trace.(1.17+build.11)
	at com.plusls.MasaGadget.malilib.util.InventoryOverlayRenderHandler.render(InventoryOverlayRenderHandler.java:50)
	at fi.dy.masa.malilib.render.InventoryOverlay.handler$zko000$renderToolTip0(InventoryOverlay.java:585)
	at fi.dy.masa.malilib.render.InventoryOverlay.renderInventoryStacks(InventoryOverlay.java:414)
	at fi.dy.masa.tweakeroo.renderer.RenderUtils.renderInventoryOverlay(RenderUtils.java:219)
	at fi.dy.masa.tweakeroo.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:44)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:66)
	at net.minecraft.client.gui.hud.InGameHud.handler$zin000$onGameOverlayPost(InGameHud:2481)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:406)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:856)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1114)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:730)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.plusls.MasaGadget.malilib.util.InventoryOverlayRenderHandler.render(InventoryOverlayRenderHandler.java:50)
	at fi.dy.masa.malilib.render.InventoryOverlay.handler$zko000$renderToolTip0(InventoryOverlay.java:585)
	at fi.dy.masa.malilib.render.InventoryOverlay.renderInventoryStacks(InventoryOverlay.java:414)
	at fi.dy.masa.tweakeroo.renderer.RenderUtils.renderInventoryOverlay(RenderUtils.java:219)
	at fi.dy.masa.tweakeroo.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:44)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:66)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['LinuxJustWorks'/21, l='ClientLevel', x=3308.80, y=63.00, z=255.79]]
	Chunk stats: 441, 225
	Level dimension: minecraft:overworld
	Level spawn location: World: (180,63,108), Section: (at 4,15,12 in 11,3,6; chunk contains blocks 176,0,96 to 191,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4573 game time, 4573 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld.java:370)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2399)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.client.MinecraftClient.modify$zil000$onCrash(MinecraftClient.java:5599)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:754)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, lambdabettergrass/default, Better Paintings.zip, Powered Noteblock.zip, Snowy Leaves.zip, Vanilla Tweaks.zip

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.2, GraalVM Community
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), GraalVM Community
	Memory: 1233125376 bytes (1176 MiB) / 2464153600 bytes (2350 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: Amber Lake
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5916
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8853
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 16936.75
	Virtual memory used (MB): 12006.45
	Swap memory total (MB): 8875.84
	Swap memory used (MB): 1062.56
	JVM Flags: 7 total; -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCIProduct -XX:-UnlockExperimentalVMOptions -XX:ThreadPriorityPolicy=1 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms128m -Xmx4096m
	Fabric Mods: 
		alternate-current: Alternate Current 0.1.4
		carpet: Carpet Mod 1.4.40
		carpet-addons: Carpet Addons 1.0.8
		carpet-extra: Carpet Extra 1.4.40
		carpet-tis-addition: Carpet TIS Addition 1.20.0+build.628
		chat-up: Chat Up! 2.0
		clientcommands: Client Commands 2.5.1
		clientcommands-scripting: Clientcommands Scripting 1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		colormatic: Colormatic 2.2.9-snapshot+mc.1.17
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		dynamicfps: Dynamic FPS 2.0.3
		entityculling: EntityCulling-Fabric 1.2.3
		fabric: Fabric API 0.35.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.1.0+1d383bb63d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+a02b44633d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b44633d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab61213d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabricloader: Fabric Loader 0.11.6
		fallingleaves: Falling Leaves 1.7.0+1.17
		g4mespeed: G4mespeed 1.1.4
		iris: Iris 1.0.2-starline
		itemscroller: Item Scroller 0.15.0-dev.20210603.144636
		java: OpenJDK 64-Bit Server VM 16
		krypton: Krypton 0.1.3
		lambdabettergrass: LambdaBetterGrass 1.2.0+1.17
		lambdynlights: LambDynamicLights 2.0.1+1.17
		lazydfu: LazyDFU 0.1.2
		litematica: Litematica 0.0.0-dev.20210603.144652
		lithium: Lithium 0.7.1
		logical_zoom: Logical Zoom 0.0.9
		lunaar-carpet-addons: Lunaar Carpet Addons 0.4.0
		malilib: MaLiLib 0.10.0+dev.22
		masa_gadget_mod: Masa Gadget 1.16.5-1.1.4
		mcg: MCG 1.2.3
		minecraft: Minecraft 1.17
		minihud: MiniHUD 0.19.0-dev.20210607.133352
		minitweaks: MiniTweaks 1.1.0
		modmenu: Mod Menu 2.0.2
		multiconnect-api: MultiConnect API 1.4
		notenoughcrashes: Not Enough Crashes 3.3.0+1.17
		ommc: Oh My Minecraft Client 1.17-0.2.7
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		rug: Rug 1.17-1.1.9
		screenshotclipboard: Screenshot to Clipboard 1.0.6
		sgui: SGui 1.0.0-rc1-1.17
		spruceui: SpruceUI 3.2.0+1.17
		starlight: Starlight fabric-1.0.0-RC2-3a77ed1
		tweak-my-client: TweakMyClient 1.1.0+build.13
		tweakeroo: Tweakeroo 1.2.1
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 620 GL version 3.2.0 - Build 27.20.100.8853, Intel
	Window size: 1920x1000
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, lambdabettergrass/default, file/Better Paintings.zip (incompatible), file/Powered Noteblock.zip (incompatible), file/Snowy Leaves.zip (incompatible), file/Vanilla Tweaks.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
	Player Count: 1 / 8; [ServerPlayerEntity['LinuxJustWorks'/21, l='ServerLevel[test]', x=3308.80, y=63.00, z=255.79]]
	Data Packs: vanilla (incompatible), Fabric Mods, file/Rug_flexibleData (incompatible)
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
```

**Comment by plusls** [comment]
已经更新了
