### ISSUE TITLE
[Bug] 1.19.2安装magiclib仍然无法启动游戏

### ISSUE THREAD

**Issue by MeowStarrySea** [plusls/MasaGadget#70]
### Minecraft Version

1.19.2

### MasaGadget Version

3.0.0

### Description

错误截图（Screenshot of the error）
![image](https://user-images.githubusercontent.com/102895780/223107080-3cc95194-492e-4617-bc1a-63c9332c1056.png)

模组列表（List of mods）
![image](https://user-images.githubusercontent.com/102895780/223107198-eb9d09ae-f891-4341-9eea-8c60d58c9113.png)

### To Reproduce

安装模组

### Log

[20:10:53] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.13
[20:10:53] [main/WARN]: Mod resolution failed
[20:10:53] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE ommc-1_19 0.5 {depends magiclib-1_19 @ [>=0.5.30]}, ROOT_FORCELOAD_SINGLE ommc-1_19 0.5]
[20:10:53] [main/INFO]: Reason: [HARD_DEP ommc-1_19 0.5 {depends magiclib-1_19 @ [>=0.5.30]}, HARD_DEP magiclib-1_14_4 0.5.37 {depends minecraft @ [1.14.x]}, HARD_DEP magiclib-1_15_2 0.5.37 {depends minecraft @ [1.15.x]}, HARD_DEP magiclib-1_16_5 0.5.37 {depends minecraft @ [1.16.x]}, HARD_DEP magiclib-1_17_1 0.5.37 {depends minecraft @ [1.17.x]}, HARD_DEP magiclib-1_18_2 0.5.37 {depends minecraft @ [1.18.x]}, HARD_DEP masa_gadget_mod-1_14_4 3.0.0 {depends minecraft @ [1.14.x]}, HARD_DEP masa_gadget_mod-1_15_2 3.0.0 {depends minecraft @ [1.15.x]}, HARD_DEP masa_gadget_mod-1_16_5 3.0.0 {depends minecraft @ [1.16.x]}, HARD_DEP masa_gadget_mod-1_17_1 3.0.0 {depends minecraft @ [1.17.x]}, HARD_DEP masa_gadget_mod-1_18_2 3.0.0 {depends minecraft @ [1.18.x]}, HARD_DEP masa_gadget_mod-1_19 3.0.0 {depends magiclib-1_19 @ [>=0.5.30]}]
[20:10:53] [main/INFO]: Fix: add [add:magiclib-1_19 0.5.30 ([[0.5.30,∞)])], remove [], replace []
[20:10:53] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install magiclib-1_19, version 0.5.30 or later.
Unmet dependency listing:
	 - Mod 'Oh My Minecraft Client for 1.19' (ommc-1_19) 0.5 requires version 0.5.30 or later of magiclib-1_19, which is missing!
	 - Mod 'MagicLib for 1.14.4' (magiclib-1_14_4) 0.5.37 requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.15.2' (magiclib-1_15_2) 0.5.37 requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.16.5' (magiclib-1_16_5) 0.5.37 requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.17.1' (magiclib-1_17_1) 0.5.37 requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.18.2' (magiclib-1_18_2) 0.5.37 requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Masa Gadget for 1.14.4' (masa_gadget_mod-1_14_4) 3.0.0 requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Masa Gadget for 1.15.2' (masa_gadget_mod-1_15_2) 3.0.0 requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Masa Gadget for 1.16.5' (masa_gadget_mod-1_16_5) 3.0.0 requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Masa Gadget for 1.17.1' (masa_gadget_mod-1_17_1) 3.0.0 requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Masa Gadget for 1.18.2' (masa_gadget_mod-1_18_2) 3.0.0 requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Masa Gadget for 1.19' (masa_gadget_mod-1_19) 3.0.0 requires version 0.5.30 or later of magiclib-1_19, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.13.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) [JavaWrapper.jar:?]

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
OMMC 版本不正确。
