### ISSUE TITLE
[Bug] 我装了MOD之后加载存档游戏就崩溃了

### ISSUE THREAD

**Issue by xiaoxingruo** [plusls/MasaGadget#81]
### Minecraft Version

1.19.4

### MasaGadget Version

3.1.289

### Description

打开存档之后就直接闪退报错了

### To Reproduce

打开存档之后就直接闪退报错了

### Log
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-05-16 20:16:05
Description: Unexpected error

java.lang.RuntimeException: Mixin transformation of fi.dy.masa.malilib.gui.widgets.WidgetListBase failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at fi.dy.masa.litematica.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:54)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:68)
	at net.minecraft.class_329.handler$zmm000$malilib$onGameOverlayPost(class_329.java:2896)
	at net.minecraft.class_329.method_1753(class_329.java:374)
	at net.minecraft.class_757.method_3192(class_757.java:918)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 19 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method drawDropDownListAgainBeforeHover(Lnet/minecraft/class_4587;IIFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in masa_gadget_mod.mixins.json:malilib.fastSwitchMasaConfigGui.MixinWidgetListBase from mod masa_gadget_mod-1_19_4 failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap MasaGadget-1.19.4-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 22 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at fi.dy.masa.litematica.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:54)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:68)
	at net.minecraft.class_329.handler$zmm000$malilib$onGameOverlayPost(class_329.java:2896)
	at net.minecraft.class_329.method_1753(class_329.java:374)

-- Affected level --
Details:
	All players: 1 total; [class_746['Xiao_Xing_Ruo'/182, l='ClientLevel', x=-36.50, y=80.00, z=-41.50]]
	Chunk stats: 961, 449
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,74,-48), Section: (at 0,10,0 in -2,4,-3; chunk contains blocks -32,-64,-48 to -17,319,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 35 game time, 35 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/Minecraft-Mod-Language-Modpack-Converted-13.zip

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 18, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1732533296 bytes (1652 MiB) / 2852126720 bytes (2720 MiB) up to 12138315776 bytes (11576 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1660
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2184
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3179
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34765.85
	Virtual memory used (MB): 20271.40
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 159.21
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx11571m
	Fabric Mods: 
		easiervillagertrading: EasierVillagerTrading 1.19.3-fabric0.68.1-1.5.4
			gbfabrictools: GBfabrictools 1.3.4+1.19.3
		fabric-api: Fabric API 0.81.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.26+1e9487d2f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.27+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.8+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.7+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.36+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.17+504944c8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.29+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.8+504944c8f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.46+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.56+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.11+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.0+c98e6b27f4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.16+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.2+504944c8f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.47+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.15+504944c8f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.5.1+76ba65ebf4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.54+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.34+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.19+504944c8f4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.7+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.34+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.32+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.17+1e9487d2f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.29+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.33+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.3+504944c8f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.41+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.32+504944c8f4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.3+504944c8f4
			fabric-networking-v0: Fabric Networking (v0) 0.3.43+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.5+504944c8f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.25+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.10+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.2+504944c8f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.7+ebc93ff3f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.2.0+ebc93ff3f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.40+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.30+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.23+504944c8f4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.43+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.3+504944c8f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.2+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.4+5ade3c38f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.47+3bd4ab0ff4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.22+504944c8f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.10+504944c8f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.0+80d07a0af4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.1.0+03ba59cef4
		fabric-language-kotlin: Fabric Language Kotlin 1.9.4+kotlin.1.8.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.19
		i18nupdatemod: I18nUpdateMod 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.9.7
		java: Java HotSpot(TM) 64-Bit Server VM 18
		libipn: libIPN 2.0.7
		litematica: Litematica 0.14.3
		magiclib: MagicLib 0.7.293+17aa28c-stable
			magiclib-1_19_4: MagicLib for 1.19.4 0.7.293+17aa28c-stable
		malilib: MaLiLib 0.15.4
		masa_gadget_mod: Masa Gadget 3.1.289+1ca4352-stable
			masa_gadget_mod-1_19_4: Masa Gadget for 1.19.4 3.1.289+1ca4352-stable
		minecraft: Minecraft 1.19.4
		minihud: MiniHUD 0.26.2
		modmenu: Mod Menu 6.1.0-rc.1
		mousetweaks: Mouse Tweaks 2.24
		tweakeroo: Tweakeroo 0.16.0
	Launched Version: 1.19.4-Fabric 0.14.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1660/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.79, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric, file/Minecraft-Mod-Language-Modpack-Converted-13.zip
	Current Language: zh_cn
	CPU: 6x Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Xiao_Xing_Ruo'/182, l='ServerLevel[新的世界]', x=-36.50, y=80.00, z=-41.50]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
```
### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Cjsah** [comment]
https://github.com/plusls/MasaGadget/actions/runs/4999554501
这不是已经解决了嘛... 直接去action里自取就好

**Comment by xiaoxingruo** [comment]
> https://github.com/plusls/MasaGadget/actions/runs/4999554501 这不是已经解决了嘛... 直接去action里自取就好

谢谢

**Comment by Hendrix-Shen** [comment]
与 #76 重复。
