### ISSUE TITLE
[Bug] 游戏里无法打开MASA系列模组的配置界面

### ISSUE THREAD

**Issue by FlameFire26** [plusls/MasaGadget#85]
### Minecraft Version

1.19.4 Fabric

### MasaGadget Version

3.1.289

### Description

如题，模组菜单（Mod menu）也显示无法加载这些模组的配置界面。

### To Reproduce

在游戏（无论单人或多人）中按MASA系列模组的打开配置快捷键会导致当场保存世界，然后窗口闪退。

### Log
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-05-28 16:04:41
Description: Unexpected error

java.lang.RuntimeException: Mixin transformation of fi.dy.masa.malilib.gui.widgets.WidgetListBase failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at fi.dy.masa.tweakeroo.config.Callbacks$KeyCallbackHotkeysGeneric.onKeyAction(Callbacks.java:405)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:185)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:145)
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:270)
	at fi.dy.masa.malilib.event.InputEventHandler.onKeyInput(InputEventHandler.java:143)
	at net.minecraft.class_309.handler$beg000$malilib$onKeyboardInput(class_309.java:2599)
	at net.minecraft.class_309.method_1466(class_309.java:331)
	at net.minecraft.class_309.lambda$setupCallbacks$8(class_309.java:738)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_309.method_22676(class_309.java:737)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:207)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:218)
	at net.minecraft.class_1041.method_15998(class_1041.java:393)
	at net.minecraft.class_310.method_1523(class_310.java:1238)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 32 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method drawDropDownListAgainBeforeHover(Lnet/minecraft/class_4587;IIFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in masa_gadget_mod.mixins.json:malilib.fastSwitchMasaConfigGui.MixinWidgetListBase from mod masa_gadget_mod-1_19_4 failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap MasaGadget-1.19.4-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 35 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at fi.dy.masa.tweakeroo.config.Callbacks$KeyCallbackHotkeysGeneric.onKeyAction(Callbacks.java:405)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:185)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:145)
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:270)
	at fi.dy.masa.malilib.event.InputEventHandler.onKeyInput(InputEventHandler.java:143)
	at net.minecraft.class_309.handler$beg000$malilib$onKeyboardInput(class_309.java:2599)
	at net.minecraft.class_309.method_1466(class_309.java:331)
	at net.minecraft.class_309.lambda$setupCallbacks$8(class_309.java:738)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_309.method_22676(class_309.java:737)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:207)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:218)

-- Affected level --
Details:
	All players: 1 total; [class_746['FlameFireZF'/1, l='ClientLevel', x=-7.50, y=-60.00, z=-2.50]]
	Chunk stats: 529, 319
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 5685 game time, 5685 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:583)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods, file/Minecraft-Mod-Language-Modpack-Converted-13.zip, file/[3D立体材质]3D.Default.1.19.4.v1.7.0, file/[UC本体]Ultimacraft-Resource-Pack-1.18.1, file/[UC立体模型]UltimaCraft_Models_(v.1.0c)_(1.17), file/[UC附魔动画]UltimaCraft_Enchantments_(b.1.0), file/[多彩界面-浅色]colourful-containers-light-mode, file/MASA全家桶汉化包, file/Xaeros-地图+OPAC模组汉化包.zip, armorchroma/alternative-icons

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 742848016 bytes (708 MiB) / 1447034880 bytes (1380 MiB) up to 5154799616 bytes (4916 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 6800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 68 Stepping 1
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1681
	Graphics card #0 versionInfo: DriverVersion=31.0.14043.7000
	Graphics card #1 name: NVIDIA GeForce RTX 2050
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x25a9
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3141
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 6.40
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 6.40
	Memory slot #1 type: Unknown
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 6.40
	Memory slot #2 type: Unknown
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 6.40
	Memory slot #3 type: Unknown
	Virtual memory max (MB): 34958.82
	Virtual memory used (MB): 30763.54
	Swap memory total (MB): 20937.87
	Swap memory used (MB): 2325.74
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx4915m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.19.4-fabric0.76.0-1.3.1
		appleskin: AppleSkin 2.4.3+mc1.19.4
		architectury: Architectury 8.1.80
		armorchroma: Armor Chroma 1.2.5
		autofish: Autofish 0.9.8-SNAPSHOT
		automaticelytra: Automatic Elytra 1.0
		betterpingdisplay: Better Ping Display 1.1.1
		bettertags: Better Tags 1.19.4-Fabric-1.1
		chat_heads: Chat Heads 0.10.14
		cherishedworlds: Cherished Worlds 6.0.5+1.19.4
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		controlling: Controlling For Fabric 11.1.3
		customskinloader: CustomSkinLoader 14.16
		eatinganimationid: Eating Animation 1.9.3
		fabric-api: Fabric API 0.80.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.25+504944c8f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.26+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.8+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.7+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.35+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.16+504944c8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.28+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.7+504944c8f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.45+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.55+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.10+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.2+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.16+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.1+504944c8f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.46+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.14+504944c8f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.5.0+76ba65ebf4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.53+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.34+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.18+504944c8f4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.6+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.34+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.32+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.16+504944c8f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.28+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.32+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.2+504944c8f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.40+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.31+504944c8f4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.2+504944c8f4
			fabric-networking-v0: Fabric Networking (v0) 0.3.42+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.4+504944c8f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.24+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.9+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.1+504944c8f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.6+504944c8f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.2+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.39+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.29+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.22+504944c8f4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.42+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.2+504944c8f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.2+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.3+1e1fb126f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.46+504944c8f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.21+504944c8f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.10+504944c8f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.2+504944c8f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.4+504944c8f4
		fabric-language-kotlin: Fabric Language Kotlin 1.9.4+kotlin.1.8.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.19
		fpsreducer: FPS Reducer 1.19.4-2.3
		i18nupdatemod: I18nUpdateMod 3.4.2
		ias: In-Game Account Switcher 8.0.1.2
		iceberg: Iceberg 1.1.10
		imblocker: IMBlockerFabric 1.0.20_pre5
		inventoryhud: Inventory HUD + 3.4.11
		inventoryprofilesnext: Inventory Profiles Next 1.9.7
		jade: Jade 10.3.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		libipn: libIPN 2.0.7
		litematica: Litematica 0.14.3
		magiclib: MagicLib 0.7.293+17aa28c-stable
			magiclib-1_19_4: MagicLib for 1.19.4 0.7.293+17aa28c-stable
		malilib: MaLiLib 0.15.4
		masa_gadget_mod: Masa Gadget 3.1.289+1ca4352-stable
			masa_gadget_mod-1_19_4: Masa Gadget for 1.19.4 3.1.289+1ca4352-stable
		minecraft: Minecraft 1.19.4
		minihud: MiniHUD 0.26.2
		modmenu: Mod Menu 6.2.2
		morechathistory: MoreChatHistory 1.1.1
		notenoughanimations: NotEnoughAnimations 1.6.3
		optifabric: OptiFabric 1.13.24
			mm: Manningham Mills 2.3
		quickshulker: Quick Shulker 1.3.10-1.19.4
			kyrptconfig: Kyrpt Config 1.5.2-1.19.4
			shulkerutils: shulkerutils 1.0.4-1.19
		roughlyenoughitems: Roughly Enough Items 11.0.597
			error_notifier: Error Notifier 1.0.9
		rrls: Remove Reloading Screen 1.5.0-fabric
		searchables: Searchables 1.0.3
		skinlayers: 3d Skin Layers 1.5.3-mc1.19.4
		smoothboot: Smooth Boot 1.19.4-1.7.0
		smoothswapping: Smooth Swapping 0.9
		torohealth: ToroHealth Damage Indicators 1.19.4-fabric-1
		tweakeroo: Tweakeroo 0.16.0
		xaerominimap: Xaero's Minimap 23.4.1
		xaeroworldmap: Xaero's World Map 1.30.1
	Launched Version: E世界
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.0 Core Profile Context 23.4.1.230326, ATI Technologies Inc.
	Window size: 2560x1506
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric, file/Minecraft-Mod-Language-Modpack-Converted-13.zip, file/[3D立体材质]3D.Default.1.19.4.v1.7.0, file/[UC本体]Ultimacraft-Resource-Pack-1.18.1 (incompatible), file/[UC立体模型]UltimaCraft_Models_(v.1.0c)_(1.17) (incompatible), file/[UC附魔动画]UltimaCraft_Enchantments_(b.1.0) (incompatible), file/[多彩界面-浅色]colourful-containers-light-mode (incompatible), file/MASA全家桶汉化包 (incompatible), file/Xaeros-地图+OPAC模组汉化包.zip (incompatible), armorchroma:alternative-icons (incompatible)
	Current Language: zh_cn
	CPU: 16x AMD Ryzen 7 6800H with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['FlameFireZF'/1, l='ServerLevel[新的世界]', x=-7.50, y=-60.00, z=-2.50]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	OptiFine Version: OptiFine_1.19.4_HD_U_I4
	OptiFine Build: 20230408-043701
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 Core Profile Context 23.4.1.230326
	OpenGlRenderer: AMD Radeon(TM) Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 16

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.19.4
	OptiFine jar version: OptiFine_1.19.4_HD_U_I4
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/26748/Desktop/E世界/.minecraft/.optifine/OptiFine_1.19.4_HD_U_I4/Optifine-mapped.jar
	OptiFabric error: <None>
```
### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
与 #76 重复，请在 GitHub Actions 中下载最新测试版。
