### ISSUE TITLE
与新版的Litematica不兼容，无法启动

### ISSUE THREAD

**Issue by MAX-XiaoKui** [plusls/MasaGadget#9]
## 游戏信息：
- Litematica版本：`0.0.0-dev.20210827.200417`和`0.0.0-dev.20210831.022621`（只在[官网](https://masa.dy.fi/mcmods/client_mods/?mcver=All)有，CurseForge没有）会崩，`0.0.0-dev.20210713.103711`能正常启动
- MaLiLib版本：`0.10.0-dev.24`
- MasaGadget版本：`1.1.6`
- Fabric-API版本：`0.38.2`、`0.39.2`、`0.40.0`都试过
- Fabric Loader版本：`0.11.6`
- Minecraft版本：`1.17.1`
使用新版的Tweakeroo（`0.10.0-dev.20210831.022634`）没有问题
## 环境信息：
系统： Windows 10 20H2
Java版本：AdoptOpenJDK `jdk-16.0.2+7_openj9-0.27.0`，也试过官方启动器的Java（应该是Microsoft build的）
## 崩溃报告：
````py
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2021/9/2 下午8:03
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.1)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at fi.dy.masa.litematica.InitHandler.registerModHandlers(InitHandler.java:28)
	at fi.dy.masa.malilib.event.InitializationHandler.onGameInitDone(InitializationHandler.java:38)
	at net.minecraft.client.MinecraftClient.handler$zlg000$onInitComplete(MinecraftClient:5063)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:637)
	at net.minecraft.client.main.Main.main(Main:179)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method modifyPlayer(Lnet/minecraft/class_1657;)Lnet/minecraft/class_1657; in masa_gadget_mod.mixins.json:litematica.feature.nudgeSelectionSupportFreeCamera.MixinInputHandler failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap MasaGadget-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at fi.dy.masa.litematica.InitHandler.registerModHandlers(InitHandler.java:28)
	at fi.dy.masa.malilib.event.InitializationHandler.onGameInitDone(InitializationHandler.java:38)
	at net.minecraft.class_310.handler$zlg000$onInitComplete(class_310.java:5063)
	at net.minecraft.class_310.<init>(class_310.java:637)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.2, International Business Machines Corporation
	Java VM Version: Eclipse OpenJ9 VM (JRE 16 Windows 10 amd64-64-Bit Compressed References 20210730_69 (JIT enabled, AOT enabled)
OpenJ9   - 1851b0074
OMR      - 9db1c870d
JCL      - 34df42439f3 based on jdk-16.0.2+7), Eclipse OpenJ9
	Memory: 248515648 bytes (237 MiB) / 713359360 bytes (680 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: SuperDisplay Virtual Adapter
	Graphics card #0 vendor: Software by KeloCube
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=3.47.17.59
	Graphics card #1 name: NVIDIA GeForce GTX 750 Ti
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x1380
	Graphics card #1 versionInfo: DriverVersion=30.0.14.7196
	Graphics card #2 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #2 vendor: NVIDIA (0x10de)
	Graphics card #2 VRAM (MB): 4095.00
	Graphics card #2 deviceId: 0x1c03
	Graphics card #2 versionInfo: DriverVersion=30.0.14.7196
	Graphics card #3 name: Intel(R) HD Graphics 630
	Graphics card #3 vendor: Intel Corporation (0x8086)
	Graphics card #3 VRAM (MB): 1024.00
	Graphics card #3 deviceId: 0x5912
	Graphics card #3 versionInfo: DriverVersion=30.0.100.9684
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.67
	Memory slot #2 type: DDR4
	Virtual memory max (MB): 65455.07
	Virtual memory used (MB): 36950.86
	Swap memory total (MB): 40960.00
	Swap memory used (MB): 2010.80
	JVM Flags: 10 total; -Xoptionsfile=C:\Program Files\Semeru\jre-16.0.2.7-openj9\lib\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx4096m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		amecsapi: Amecs API 1.1.5+mc21w16a
		appleskin: AppleSkin mc1.17-2.1.0
		architectury: Architectury 2.5.27
		autofish: Autofish 0.9.3
		baritone: Baritone 1.7.0
		bbor: BoundingBoxOutlineReloaded 2.4-1.17.1
		betterf3: BetterF3 1.1.5
		bettersodiumvideosettingsbutton: Better Sodium Video Settings Button 2.0.0
		bobby: Bobby 2.0.4
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.3.0
		cameraoverhaul: Camera Overhaul 1.2.2-fabric-universal
		carpet: Carpet Mod 1.4.45
		carpet-extra: Carpet Extra 1.4.43
		carpet-tis-addition: Carpet TIS Addition 1.21.2+build.655
		cherishedworlds: Cherished Worlds 2.0.1-1.17.1
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		colormeoutlines: Color Me Outlines 1.0.1
		com_github_wearblackallday_javautils: JavaUtils 1b369d41cd
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		confabricate: confabricate 2.1.0-SNAPSHOT+4.1.1
		ctm: ConnectedTexturesMod for Fabric 0.5.1+1.17
		cullleaves: Cull Leaves 2.2.0
		custom-crosshair-mod: Custom Crosshair Mod 1.3.3-fabric
		customskinloader: CustomSkinLoader 14.13-SNAPSHOT-282
		dimthread: DimensionalThreading 1.2.5
		dontdropit: Don't Drop It! 2.3.1+1.17
		dynamicfps: Dynamic FPS 2.0.5
		easiervillagertrading: EasierVillagerTrading 1.17.1-fabric0.36.1-1.5.4
		enhancedblockentities: Enhanced Block Entities 0.4.1+1.17
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.39.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+2f75c6ce18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+b06cb95b18
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+211ddf9518
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.2+62e33f4118
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.4+kotlin.1.5.30
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.1+b06cb95b18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.0+b06cb95b18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.1.2+96bf6a7e18
		fabricloader: Fabric Loader 0.11.6
		fabrishot: Fabrishot 1.5.1
		fallingleaves: Falling Leaves 1.7.3+1.17.1
		fastfurnace: FastFurnace 1.17-3.0
		fiber: fiber 0.23.0-2
		gbfabrictools: GBfabrictools 1.3.4+1.17
		horseinfo: Horse Info 0.3.0-1.17
		hydrogen: Hydrogen 0.3
		ias: In-Game Account Switcher 7.1.1
		illuminations: Illuminations 1.6.3
		imblocker: IMBlockerFabric 1.0.14
		inventoryhud: Inventory HUD + 3.3.2
		inventoryprofilesnext: Inventory Profiles Next 1.0.0
		invmove: InvMove 1.17-0.0.1-r1
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.1.1
		itemmodelfix: Item Model Fix 1.0.2+1.17
		itemscroller: Item Scroller 0.15.0-dev.20210707.005506
		java: Eclipse OpenJ9 VM 16
		krypton: Krypton 0.1.4
		lambdynlights: LambDynamicLights 2.0.2+1.17
		libzoomer: LibZoomer 0.2.1+1.17
		litematica: Litematica 0.0.0-dev.20210827.200417
		lithium: Lithium 0.7.4
		malilib: MaLiLib 0.10.0-dev.24
		masa_gadget_mod: Masa Gadget 1.17-1.1.6
		mcwifipnp: Minecraft WLAN Plug-n-Play 1.4.7
		memoryusagescreen: Memory Usage Screen 1.1
		minecraft: Minecraft 1.17.1
		minihud: MiniHUD 0.19.0-dev.20210707.150016
		modmanager: Mod Manager 1.0.1+1.17-alpha
		modmenu: Mod Menu 2.0.6
		multiconnect: MultiConnect 1.4.14
		multiconnect-api: MultiConnect API 1.4.14
		notenoughcrashes: Not Enough Crashes 3.4.4+1.17
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		ommc: Oh My Minecraft Client 1.17.1-0.3.3
		orderly: Orderly 2.0.0-alpha.10+custom-1.17
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		pistorder: Pistorder 1.4.2
		quitconfirm: QuitConfirm 1.3
		replaymod: Replay Mod 1.17.1-2.6.1
		roughlyenoughitems: Roughly Enough Items 6.0.279-alpha
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.3.0+IRIS2
		sodium-extra: Sodium Extra 0.3.4
		spruceui: SpruceUI 3.2.0+1.17
		starlight: Starlight 1.0.0-RC3+fabric.2b7d7ae
		torohealth: ToroHealth Damage Indicators 1.17-fabric-6
		tweakeroo: Tweakeroo 0.10.0-dev.20210819.012739
		voxelmap: VoxelMap 1.10.15
		worldedit: WorldEdit 7.2.6-beta-01+1415e6f
		wthit: wthit 3.8.1
	Launched Version: 1.17.1-Fabric 0.11.6
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 750 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.96, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Suspected Mods: Litematica (litematica), MaLiLib (malilib), Fabric Loader (fabricloader)
````

**Comment by plusls** [comment]
这是一个已知的问题，可以尝试这个版本

由于目前 MasaGadget 正在重构，因此不会立刻修复

[MasaGadget.zip](https://github.com/plusls/MasaGadget/files/7099030/MasaGadget.zip)

**Comment by MAX-XiaoKui** [comment]
谢谢，已经成功启动

**Comment by plusls** [comment]
fixed
