### ISSUE TITLE
村民渲染会闪退

### ISSUE THREAD

**Issue by linyiyi1314** [plusls/MasaGadget#92]
### Question Type

Codes

### Description
```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2023-07-06 03:09:11
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1646.method_37908()" because "villager" is null
	at com.plusls.MasaGadget.generic.entityInfo.VillagerNextRestockTimeInfo.getInfo(VillagerNextRestockTimeInfo.java:16)
	at com.plusls.MasaGadget.generic.entityInfo.EntityInfoRenderer.render(EntityInfoRenderer.java:44)
	at top.hendrixshen.magiclib.event.render.impl.RenderEventHandler.lambda$dispatchPostRenderLevelEvent$1(RenderEventHandler.java:48)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at top.hendrixshen.magiclib.event.render.impl.RenderEventHandler.dispatchPostRenderLevelEvent(RenderEventHandler.java:46)
	at net.minecraft.class_761.handler$dee000$magiclib-1_20_1$postRenderLevel(class_761.java:11457)
	at net.minecraft.class_761.method_22710(class_761.java:1553)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.plusls.MasaGadget.generic.entityInfo.VillagerNextRestockTimeInfo.getInfo(VillagerNextRestockTimeInfo.java:16)
	at com.plusls.MasaGadget.generic.entityInfo.EntityInfoRenderer.render(EntityInfoRenderer.java:44)
	at top.hendrixshen.magiclib.event.render.impl.RenderEventHandler.lambda$dispatchPostRenderLevelEvent$1(RenderEventHandler.java:48)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at top.hendrixshen.magiclib.event.render.impl.RenderEventHandler.dispatchPostRenderLevelEvent(RenderEventHandler.java:46)
	at net.minecraft.class_761.handler$dee000$magiclib-1_20_1$postRenderLevel(class_761.java:11457)
	at net.minecraft.class_761.method_22710(class_761.java:1553)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

-- Affected level --
Details:
	All players: 2 total; [class_746['linyi_yi'/119, l='ClientLevel', x=-166.56, y=63.00, z=52.18], class_745['Mifeng'/121, l='ClientLevel', x=-189.51, y=61.00, z=56.34]]
	Chunk stats: 1024, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (96,63,112), Section: (at 0,15,0 in 6,3,7; chunk contains blocks 96,-64,112 to 111,319,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 5410538 game time, 5897530 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, armorchroma:alternative-icons, continuity:default, file/XeKr 原版红显16~19plus2.4.zip, file/护眼大补丸1.19.zip, file/ikun不食油饼.zip, file/Hardcore+Hearts+1.11-1.12.2.zip, file/Minecraft-Mod-Language-Modpack-Converted-1.20.1.zip, file/坤坤图腾.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 18.0.1.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2244468440 bytes (2140 MiB) / 4294967296 bytes (4096 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12500H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: Alder Lake
	Frequency (GHz): 3.11
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2560
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2799
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 26432.86
	Virtual memory used (MB): 16254.86
	Swap memory total (MB): 10240.00
	Swap memory used (MB): 57.68
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx8192m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.20-fabric0.83.0-1.4
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.0.8
		armorchroma: Armor Chroma 1.2.6
		betterf3: BetterF3 7.0.0
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.91
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.91
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.91
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.91
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.91
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.91
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.91
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.91
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.91
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.91
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.91
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.91
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.91
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.91
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.91
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.10.91
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.91
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.91
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.91
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.91
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.91
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		carpet: Carpet Mod 1.4.112+v230608
		cloth-config: Cloth Config v11 11.0.99
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.2+1.20
		controlling: Controlling For Fabric 12.0.1
		customskinloader: CustomSkinLoader 14.17
		dynamicfps: Dynamic FPS 2.4.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		fabric-api: Fabric API 0.85.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a77
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.0+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.8+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.12+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.8+40e50c4677
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.38+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.42+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.48+b3afc78b77
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.0+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.0+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.0+c154966e77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c154966e77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
```

**Comment by Hendrix-Shen** [comment]
与 #91 重复。
